# devcontainer and external playwright test runner

services:
  dev:
    image: mcr.microsoft.com/devcontainers/typescript-node
    volumes: [
      ".:/workspace",
      "/workspace/node_modules",
    ]
    working_dir: /workspace
    env:
      - PW_TEST_CONNECT_WS_ENDPOINT=ws://playwright:3000/

  playwright:
    image: mcr.microsoft.com/playwright
    ports: ["3000:3000"]
    command: ["npx", "-y", "playwright", "run-server", "--port", "3000", "--host", "0.0.0.0"]