name: CO₂
on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  co2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/cache@v4
        with:
          path: baseline.co2
          key: baseline-co2-${{ github.sha }}
          restore-keys: |
            baseline-co2-
      - name: Detect CO₂ regression
        run: npm run co2
        env:
          CO2_BASELINE: 0.1
          TARGET_URL: https://leolem.dev
