name: Deploy, Smoke Test, and CO2 Calculation

permissions:
  contents: read

on:
  push:
    branches: [tests, main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/cache@v3
        with:
          path: dist
          key: build-dist-${{ github.sha }}
          restore-keys: build-dist-
          fail-on-cache-miss: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  smoke:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npx playwright install
      - name: Run Playwright smoke tests
        run: npx playwright test test/smoke.spec.ts
        env:
          BASE_URL: https://leolem.dev
      - name: Publish Playwright Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Playwright Tests
          path: test-results.xml
          reporter: java-junit

  coo2:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Check CO2 regression
        run: node scripts/check-co2.js
        env:
          TARGET_URL: https://leolem.dev
          BASELINE_CO2: 0.05 # Adjust baseline (grams) as needed
