name: PR Build and Local Smoke Test
on:
  pull_request:
    branches: [main]
    paths-ignore: ["README.md", ".github/dependabot.yml", ".devcontainer.json", ".github/workflows/main.yml"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run build
      - uses: actions/cache@v3
        with:
          path: dist
          key: build-dist-${{ github.sha }}

  smoke:
    permissions:
      actions: read
      checks: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/cache@v3
        with:
          path: dist
          key: build-dist-${{ github.sha }}
          restore-keys: build-dist-
      - run: npx playwright install
      - name: Run local Playwright tests
        run: |
          npx serve dist & # serve build
          sleep 5
          npx playwright test
        env:
          BASE_URL: http://localhost:3000
      - name: Publish Playwright Test Results
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Playwright Tests
          path: test-results.xml
          reporter: java-junit
