name: PR Build and Local Smoke Test

on:
  push: # TODO: change to pull_request when ready
    branches: [tests, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run build
      - uses: actions/cache@v3
        with:
          path: dist
          key: build-dist-${{ github.sha }}

  smoke:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/cache@v3
        with:
          path: dist
          key: build-dist-${{ github.sha }}
          restore-keys: build-dist-
      - run: npx playwright install
      - name: Run local Playwright tests
        run: |
          npx serve dist & # serve build
          sleep 5
          npx playwright test
        env:
          BASE_URL: http://localhost:3000