name: PR Build and Local Smoke Test

on:
  push: # TODO: change to pull_request when ready
    branches: [tests, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: dist
          name: site-dist

  smoke:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist
      - run: npx playwright install
      - name: Run local Playwright tests
        run: |
          npx serve dist & # serve build
          sleep 5
          npx playwright test
        env:
          BASE_URL: http://localhost:3000